### ISSUE TITLE
프로토타입 및 기초 필요사항 준비

### ISSUE THREAD

**Issue by w00shh** [W00SHH/W00SHH.github.io#1]
안녕하세요. 해야할 일 몇 개 추려서 올려드립니다.

본래 역할분배를 대략적으로 했었지만, 역할분배 그대로 가기보다는 다 같이 나눠하는게 좋을 것 같아, 

github issue로 올려드립니다.

본래는 성적증명서를 읽어오자고 제안했었지만, 성적증명서를 이용하려면 다음과 같은 문제가 있습니다:

1. 500원의 수수료
2. PDF를 읽어 파싱하는 것이 생각보다 어려움.

성적증명서 말고도, GLS에서 엑셀로 불러올 수 있는 방법이 있어, 해당 방법을 이용하면 좋을 것 같습니다.

성적 관련 엑셀은 [GLS - 전공별성적 - 교과목 우클릭 - 엑셀 다운로드 / 엑셀 다운로드(서식제외)를 클릭하면 엑셀 파일을 받을 수 있습니다.

대략적으로 테스트 해보니, Python의 Pandas를 활용하면, 쉽게 가능할 것 같습니다.

Pandas 또는 Python에 익숙하신 분이 이 업무를 수행하시면 좋을 것 같습니다.

제가 대략적으로 생각한 요구사항은 다음과 같습니다:

- [x]  엑셀파일에서 유저의 이수과목 읽기 및 저장 → 배열형태, 딕셔너리 형태로 저장?
    
    → 학점이 F과 같은 예외처리 필요
    
- [x]  과목 데이터베이스 구축
    
    크롤링을 해도 좋지만, 방법을 모르겠으면 직접 수기로 일일히 데이터를 입력하는 것도 하나의 방안이지만 매우 시간이 오래걸릴 것 같습니다.
    
    [GLS - 학사과정-교양과목조회 / 학사-전공과목] 탭에서 교양 및 전공 구분을 확인할 수 있습니다.
    
    SQL로 구분하여도 좋고, 파이썬이나 자바스크립트의 자료구조로 저장해도 좋을 것 같습니다.
    
- [x]  웹 대략적인 프레임 제작
    
    말 그대로 대략적인 프로토타입을 제작하는 것입니다. 부트스트랩을 사용하면 좋을 것 같습니다.
    

저도 개발을 해본 경험이 없어서, 제가 생각한 방안 말고도, 더 좋은 방안이 있으면 의견을 남겨주시면 감사하겠습니다.

**Comment by w00shh** [comment]
저는 프로토타입 제작하겠습니다.

**Comment by YunchaeChoi** [comment]
저는 그럼 엑셀파일 읽어오기로 하겠습니다.
